# Tomcat
server.port: 8080

# Logging level (TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF)
logging:
    level:
        org.hibernate: WARN
        org.springframework: WARN
    file: SpringData.log

# spring
spring:
    freemarker.cache: false
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/springData?characterEncoding=utf8
        username: root
        password: 353441055
    jpa:
        show-sql: true
        hibernate:
            # Hibernate DDL  auto: create, create-drop, update, validate
            ddl-auto: validate
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
            properties:
                hibernate.dialect: org.hibernate.dialect.MySQL5Dialect